routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::group(['middleware' => 'auth'], function () {
	Route::get('/', 'HomeController@index')->name('home');
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);

	Route::resource('jabatan', 'JabatanController');
	Route::resource('golongan', 'GolonganController');
	Route::resource('eselon', 'EselonController');
	Route::resource('jabatan-struktural', 'JabatanStrukturalController');
	Route::resource('jabatan-fungsional', 'JabatanFungsionalController');
	Route::resource('gaji-pokok', 'GajiPokokController');

	Route::resource('jusuran-pendidikan', 'JusuranPendidikanController');
	Route::resource('strata-pendidikan', 'StrataPendidikanController');
	Route::resource('diklat-profesi', 'DiklatProfesiController');
	Route::resource('diklat-fungsional', 'DiklatFungsionalController');
	Route::resource('diklat-fungsional', 'DiklatFungsionalController');
	Route::resource('diklat-struktural', 'DiklatStrukturalController');
	Route::resource('pegawai', 'PegawaiController');


	Route::get('kota/{provinsiID}', 'WilayahController@getKota');
	Route::get('kecamatan/{kotaID}', 'WilayahController@getKecamatan');




});

app/Golongan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Golongan extends Model
{
    public $timestamps = false;
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 't_gol';

    public $primaryKey  = 'fc_kdgol';
  
    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['fc_kdgol', 'fc_ruang', 'fv_nmjab'];

    
}

app/Http/Controllers/GolonganController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Http\Requests;

use App\Golongan;
use Illuminate\Http\Request;

class GolonganController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\View\View
     */
    public function index(Request $request)
    {
        $keyword = $request->get('search');
        $perPage = 25;

        if (!empty($keyword)) {
            $golongan = Golongan::where('fc_kdgol', 'LIKE', "%$keyword%")
                ->orWhere('fc_ruang', 'LIKE', "%$keyword%")
                ->orWhere('fv_nmjab', 'LIKE', "%$keyword%")
                ->paginate($perPage);
        } else {
            $golongan = Golongan::paginate($perPage);
        }

        return view('golongan.index', compact('golongan'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        return view('golongan.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {
        
        $this->validate($request, [
            'fc_kdgol' => 'required',
            'fc_ruang' => 'required|max:5',
            'fv_nmjab' => 'required|max:50'
        ]);
        
        $requestData = $request->all();
        
        Golongan::create($requestData);

        return redirect('golongan')->with('flash_message', 'Golongan added!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     *
     * @return \Illuminate\View\View
     */
    public function show($id)
    {
        $golongan = Golongan::findOrFail($id);

        return view('golongan.show', compact('golongan'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     *
     * @return \Illuminate\View\View
     */
    public function edit($id)
    {
        $golongan = Golongan::where('fc_kdgol',$id)->first();

        return view('golongan.edit', compact('golongan'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param  int  $id
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'fc_kdgol' => 'required',
            'fc_ruang' => 'required|max:5',
            'fv_nmjab' => 'required|max:50'
        ]);
        
        $requestData = $request->all();

        $golongan = Golongan::where('fc_kdgol',$id)->first();

        $golongan->update([
            'fc_kdgol' => $request->fc_kdgol,
            'fc_ruang' => $request->fc_ruang,
            'fv_nmjab' => $request->fv_nmjab
        ]);

        return redirect('golongan')->with('flash_message', 'Golongan updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy($id)
    {
        Golongan::where('fc_kdgol',$id)->delete($id);

        return redirect('golongan')->with('flash_message', 'Golongan deleted!');
    }
}

resources/views/golongan/create.blade.php
@extends('layouts.app', ['activePage' => 'golongan', 'titlePage' => __('Golongan')])


@section('content')
<div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Create New Golongan</div>
                <div class="card-body">
                    <a href="{{ url('/golongan') }}" title="Back"><button class="btn btn-warning btn-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> Back</button></a>
                    <br />
                    <br />

                    @if ($errors->any())
                    <div class="alert alert-danger"  role="alert">
                        <ul >
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                    <br>
                    <br>
                        
                    @endif

                    <form method="POST" action="{{ url('/golongan') }}" accept-charset="UTF-8" class="form-horizontal" enctype="multipart/form-data">
                        {{ csrf_field() }}

                        @include ('golongan.form', ['formMode' => 'create'])

                    </form>

                </div>
            </div>
        </div>
    </div>
    </div>
</div>
@endsection

resources/views/golongan/edit.blade.php
@extends('layouts.app', ['activePage' => 'golongan', 'titlePage' => __('Golongan')])


@section('content')
<div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Edit Golongan #{{ $golongan->id }}</div>
                <div class="card-body">
                    <a href="{{ url('/golongan') }}" title="Back"><button class="btn btn-warning btn-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> Back</button></a>
                    <br />
                    <br />

                    @if ($errors->any())
                    <div class="alert alert-danger"  role="alert">
                        <ul >
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                    <br>
                    <br>
                    @endif

                    <form action="{{ route('golongan.update',$golongan->fc_kdgol) }}" method="POST">
                            @csrf
                            @method('PUT')

                        @include ('golongan.form', ['formMode' => 'edit'])

                    </form>

                </div>
            </div>
        </div>
    </div>
    </div>
</div>
@endsection

resources/views/golongan/form.blade.php
<div class="form-group {{ $errors->has('fc_kdgol') ? 'has-error' : ''}}">
    <label for="fc_kdgol" class="control-label">{{ 'Fc Kdgol' }}</label>
    <input class="form-control" name="fc_kdgol" type="text" id="fc_kdgol" value="{{ isset($golongan->fc_kdgol) ? $golongan->fc_kdgol : ''}}" >
    {!! $errors->first('fc_kdgol', '<p class="help-block">:message</p>') !!}
</div>
<div class="form-group {{ $errors->has('fc_ruang') ? 'has-error' : ''}}">
    <label for="fc_ruang" class="control-label">{{ 'Fc Ruang' }}</label>
    <input class="form-control" name="fc_ruang" type="text" id="fc_ruang" value="{{ isset($golongan->fc_ruang) ? $golongan->fc_ruang : ''}}" >
    {!! $errors->first('fc_ruang', '<p class="help-block">:message</p>') !!}
</div>
<div class="form-group {{ $errors->has('fv_nmjab') ? 'has-error' : ''}}">
    <label for="fv_nmjab" class="control-label">{{ 'Fv Nmjab' }}</label>
    <input class="form-control" name="fv_nmjab" type="text" id="fv_nmjab" value="{{ isset($golongan->fv_nmjab) ? $golongan->fv_nmjab : ''}}" >
    {!! $errors->first('fv_nmjab', '<p class="help-block">:message</p>') !!}
</div>


<div class="form-group">
    <input class="btn btn-primary" type="submit" value="{{ $formMode === 'edit' ? 'Update' : 'Create' }}">
</div>

resources/views/golongan/index.blade.php
@extends('layouts.app', ['activePage' => 'golongan', 'titlePage' => __('Golongan')])


@section('content')
  <div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Golongan</div>
                    <div class="card-body">
                        <a href="{{ url('/golongan/create') }}" class="btn btn-success btn-sm" title="Add New Golongan">
                            <i class="fa fa-plus" aria-hidden="true"></i> Add New
                        </a>

                        <form method="GET" action="{{ url('/golongan') }}" accept-charset="UTF-8" class="form-inline my-2 my-lg-0 float-right" role="search">
                            <div class="input-group">
                                <input type="text" class="form-control" name="search" placeholder="Search..." value="{{ request('search') }}">
                                <span class="input-group-append">
                                    <button class="btn btn-secondary" type="submit">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                        </form>

                        <br/>
                        <br/>
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                       <th>Fc Kdgol</th><th>Fc Ruang</th><th>Fv Nmjab</th><th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                @foreach($golongan as $item)
                                    <tr>
                                        <td>{{ $item->fc_kdgol }}</td><td>{{ $item->fc_ruang }}</td><td>{{ $item->fv_nmjab }}</td>
                                        <td>
                                            <a href="{{ url('/golongan/' . $item->fc_kdgol . '/edit') }}" title="Edit Golongan"><button class="btn btn-primary btn-sm"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit</button></a>

                                            <form method="POST" action="{{ url('/golongan' . '/' . $item->fc_kdgol) }}" accept-charset="UTF-8" style="display:inline">
                                                {{ method_field('DELETE') }}
                                                {{ csrf_field() }}
                                                <button type="submit" class="btn btn-danger btn-sm" title="Delete Golongan" onclick="return confirm(&quot;Confirm delete?&quot;)"><i class="fa fa-trash-o" aria-hidden="true"></i> Delete</button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                            <div class="pagination-wrapper"> {!! $golongan->appends(['search' => Request::get('search')])->render() !!} </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/golongan/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            @include('admin.sidebar')

            <div class="col-md-9">
                <div class="card">
                    <div class="card-header">Golongan {{ $golongan->id }}</div>
                    <div class="card-body">

                        <a href="{{ url('/golongan') }}" title="Back"><button class="btn btn-warning btn-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> Back</button></a>
                        <a href="{{ url('/golongan/' . $golongan->id . '/edit') }}" title="Edit Golongan"><button class="btn btn-primary btn-sm"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit</button></a>

                        <form method="POST" action="{{ url('golongan' . '/' . $golongan->id) }}" accept-charset="UTF-8" style="display:inline">
                            {{ method_field('DELETE') }}
                            {{ csrf_field() }}
                            <button type="submit" class="btn btn-danger btn-sm" title="Delete Golongan" onclick="return confirm(&quot;Confirm delete?&quot;)"><i class="fa fa-trash-o" aria-hidden="true"></i> Delete</button>
                        </form>
                        <br/>
                        <br/>

                        <div class="table-responsive">
                            <table class="table">
                                <tbody>
                                    <tr>
                                        <th>ID</th><td>{{ $golongan->id }}</td>
                                    </tr>
                                    <tr><th> Fc Kdgol </th><td> {{ $golongan->fc_kdgol }} </td></tr><tr><th> Fc Ruang </th><td> {{ $golongan->fc_ruang }} </td></tr><tr><th> Fv Nmjab </th><td> {{ $golongan->fv_nmjab }} </td></tr>
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection