routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::group(['middleware' => 'auth'], function () {
	Route::get('/', 'HomeController@index')->name('home');
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);

	Route::resource('jabatan', 'JabatanController');
	Route::resource('golongan', 'GolonganController');
	Route::resource('eselon', 'EselonController');
	Route::resource('jabatan-struktural', 'JabatanStrukturalController');
	Route::resource('jabatan-fungsional', 'JabatanFungsionalController');
	Route::resource('gaji-pokok', 'GajiPokokController');

	Route::resource('jusuran-pendidikan', 'JusuranPendidikanController');
	Route::resource('strata-pendidikan', 'StrataPendidikanController');
	Route::resource('diklat-profesi', 'DiklatProfesiController');
	Route::resource('diklat-fungsional', 'DiklatFungsionalController');
	Route::resource('diklat-fungsional', 'DiklatFungsionalController');
	Route::resource('diklat-struktural', 'DiklatStrukturalController');
	Route::resource('pegawai', 'PegawaiController');


	Route::get('kota/{provinsiID}', 'WilayahController@getKota');
	Route::get('kecamatan/{kotaID}', 'WilayahController@getKecamatan');




});

app/GajiPokok.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class GajiPokok extends Model
{
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 't_gaji';

    /**
    * The database primary key value.
    *
    * @var string
    */
    protected $primaryKey = null;
    public $incrementing = false;
    public $timestamps = false;
    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['fc_periode', 'fc_kdgaji', 'fm_gaji'];

    
}

app/Http/Controllers/GajiPokokController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Http\Requests;

use App\GajiPokok;
use Illuminate\Http\Request;

class GajiPokokController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\View\View
     */
    public function index(Request $request)
    {
        $keyword = $request->get('search');
        $perPage = 25;

        if (!empty($keyword)) {
            $gajipokok = GajiPokok::where('fc_periode', 'LIKE', "%$keyword%")
                ->orWhere('fc_kdgaji', 'LIKE', "%$keyword%")
                ->orWhere('fm_gaji', 'LIKE', "%$keyword%")
                ->paginate($perPage);
        } else {
            $gajipokok = GajiPokok::paginate($perPage);
        }

        return view('gaji-pokok.index', compact('gajipokok'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        return view('gaji-pokok.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'fc_periode' => 'required|:max:6',
            'fc_kdgaji' => 'required|max:4',
            'fm_gaji' => 'required',
        ]);
        
        $requestData = $request->except(['_token','_method']);
     
        GajiPokok::create($requestData);

        return redirect('gaji-pokok')->with('flash_message', 'GajiPokok added!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     *
     * @return \Illuminate\View\View
     */
    public function show($id)
    {
        $gajipokok = GajiPokok::findOrFail($id);

        return view('gaji-pokok.show', compact('gajipokok'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     *
     * @return \Illuminate\View\View
     */
    public function edit($id)
    {
        $gajipokok = GajiPokok::where('fc_kdgaji',$id)
                                ->where('fc_periode',request()->fc_periode)
                                ->first();


        return view('gaji-pokok.edit', compact('gajipokok'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param  int  $id
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'fm_gaji' => 'required',
        ]);

        $requestData = $request->except(['_token','_method']);
        
        $gajipokok = GajiPokok::where('fc_kdgaji',$id)
                                ->where('fc_periode',request()->fc_periode);

                                
        $gajipokok->update($requestData);

        return redirect('gaji-pokok')->with('flash_message', 'GajiPokok updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy($id)
    {
        GajiPokok::where('fc_kdgaji',$id)
                    ->where('fc_periode',request()->fc_periode)
                    ->delete();

        return redirect('gaji-pokok')->with('flash_message', 'GajiPokok deleted!');
    }
}

resources/views/gaji-pokok/create.blade.php
@extends('layouts.app', ['activePage' => 'gaji-pokok', 'titlePage' => __('Gaji Pokok')])


@section('content')
<div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
             <div class="card">
                    <div class="card-header">Create New Gaji Pokok</div>
                    <div class="card-body">
                        <a href="{{ url('/gaji-pokok') }}" title="Back"><button class="btn btn-warning btn-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> Back</button></a>
                        <br />
                        <br />

                        @if ($errors->any())
                        <div class="alert alert-danger"  role="alert">
                            <ul >
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                        <br>
                        @endif

                        <form method="POST" action="{{ url('/gaji-pokok') }}" accept-charset="UTF-8" class="form-horizontal" enctype="multipart/form-data">
                            {{ csrf_field() }}

                            @include ('gaji-pokok.form', ['formMode' => 'create'])

                        </form>

                    </div>
                </div>
        </div>
    </div>
    </div>
</div>
@endsection

resources/views/gaji-pokok/edit.blade.php
@extends('layouts.app', ['activePage' => 'gaji-pokok', 'titlePage' => __('Gaji Pokok')])


@section('content')
<div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
            <div class="card">
                    <div class="card-header">Edit GajiPokok #{{ $gajipokok->fc_kdgaji }}</div>
                    <div class="card-body">
                        <a href="{{ url('/gaji-pokok') }}" title="Back"><button class="btn btn-warning btn-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> Back</button></a>
                        <br />
                        <br />

                       @if ($errors->any())
                        <div class="alert alert-danger"  role="alert">
                            <ul >
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                        <br>
                        @endif

                        <form action="{{ route('gaji-pokok.update',$gajipokok->fc_kdgaji) }}" method="POST">
                            @csrf
                            @method('PUT')

                            @include ('gaji-pokok.form', ['formMode' => 'edit'])

                        </form>

                    </div>
                </div>
        </div>
    </div>
    </div>
</div>
@endsection

resources/views/gaji-pokok/form.blade.php
<div class="form-group {{ $errors->has('fc_periode') ? 'has-error' : ''}}">
    <label for="fc_periode" class="control-label">{{ 'Fc Periode' }}</label>
    <input class="form-control" name="fc_periode" type="text" id="fc_periode" value="{{ isset($gajipokok->fc_periode) ? $gajipokok->fc_periode : ''}}"   disabled="{{ $formMode === 'edit' ? 'true' : '' }}">
    {!! $errors->first('fc_periode', '<p class="help-block">:message</p>') !!}
</div>
<div class="form-group {{ $errors->has('fc_kdgaji') ? 'has-error' : ''}}">
    <label for="fc_kdgaji" class="control-label">{{ 'Fc Kdgaji' }}</label>
    <input class="form-control" name="fc_kdgaji" type="text" id="fc_kdgaji" value="{{ isset($gajipokok->fc_kdgaji) ? $gajipokok->fc_kdgaji : ''}}"   disabled="{{ $formMode === 'edit' ? 'true' : '' }}" >
    {!! $errors->first('fc_kdgaji', '<p class="help-block">:message</p>') !!}
</div>
<div class="form-group {{ $errors->has('fm_gaji') ? 'has-error' : ''}}">
    <label for="fm_gaji" class="control-label">{{ 'Fm Gaji' }}</label>
    <input class="form-control" name="fm_gaji" type="text" id="fm_gaji" value="{{ isset($gajipokok->fm_gaji) ? $gajipokok->fm_gaji : ''}}" >
    {!! $errors->first('fm_gaji', '<p class="help-block">:message</p>') !!}
</div>


<div class="form-group">
    <input class="btn btn-primary" type="submit" value="{{ $formMode === 'edit' ? 'Update' : 'Create' }}">
</div>

resources/views/gaji-pokok/index.blade.php
@extends('layouts.app', ['activePage' => 'gaji-pokok', 'titlePage' => __('Gaji Pokok')])

@section('content')
  <div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Gaji Pokok</div>
                    <div class="card-body">
                        <a href="{{ url('/gaji-pokok/create') }}" class="btn btn-success btn-sm" title="Add New GajiPokok">
                            <i class="fa fa-plus" aria-hidden="true"></i> Add New
                        </a>

                        <form method="GET" action="{{ url('/gaji-pokok') }}" accept-charset="UTF-8" class="form-inline my-2 my-lg-0 float-right" role="search">
                            <div class="input-group">
                                <input type="text" class="form-control" name="search" placeholder="Search..." value="{{ request('search') }}">
                                <span class="input-group-append">
                                    <button class="btn btn-secondary" type="submit">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                        </form>

                        <br/>
                        <br/>
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                       <th>Fc Periode</th><th>Fc Kdgaji</th><th>Fm Gaji</th><th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                @foreach($gajipokok as $item)
                                    <tr>
                                        <td>{{ $item->fc_periode }}</td><td>{{ $item->fc_kdgaji }}</td><td>{{ $item->fm_gaji }}</td>
                                        <td>
                                            <a href="{{ url('/gaji-pokok/' . $item->fc_kdgaji . '/edit'.'?fc_periode='. $item->fc_periode) }}" title="Edit GajiPokok"><button class="btn btn-primary btn-sm"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit</button></a>

                                            <form method="POST" action="{{ url('/gaji-pokok' . '/' . $item->fc_kdgaji.'?fc_periode='. $item->fc_periode) }}" accept-charset="UTF-8" style="display:inline">
                                                {{ method_field('DELETE') }}
                                                {{ csrf_field() }}
                                                <button type="submit" class="btn btn-danger btn-sm" title="Delete GajiPokok" onclick="return confirm(&quot;Confirm delete?&quot;)"><i class="fa fa-trash-o" aria-hidden="true"></i> Delete</button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                            <div class="pagination-wrapper"> {!! $gajipokok->appends(['search' => Request::get('search')])->render() !!} </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/gaji-pokok/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            @include('admin.sidebar')

            <div class="col-md-9">
                <div class="card">
                    <div class="card-header">GajiPokok {{ $gajipokok->id }}</div>
                    <div class="card-body">

                        <a href="{{ url('/gaji-pokok') }}" title="Back"><button class="btn btn-warning btn-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> Back</button></a>
                        <a href="{{ url('/gaji-pokok/' . $gajipokok->id . '/edit') }}" title="Edit GajiPokok"><button class="btn btn-primary btn-sm"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit</button></a>

                        <form method="POST" action="{{ url('gajipokok' . '/' . $gajipokok->id) }}" accept-charset="UTF-8" style="display:inline">
                            {{ method_field('DELETE') }}
                            {{ csrf_field() }}
                            <button type="submit" class="btn btn-danger btn-sm" title="Delete GajiPokok" onclick="return confirm(&quot;Confirm delete?&quot;)"><i class="fa fa-trash-o" aria-hidden="true"></i> Delete</button>
                        </form>
                        <br/>
                        <br/>

                        <div class="table-responsive">
                            <table class="table">
                                <tbody>
                                    <tr>
                                        <th>ID</th><td>{{ $gajipokok->id }}</td>
                                    </tr>
                                    <tr><th> Fc Periode </th><td> {{ $gajipokok->fc_periode }} </td></tr><tr><th> Fc Kdgaji </th><td> {{ $gajipokok->fc_kdgaji }} </td></tr><tr><th> Fm Gaji </th><td> {{ $gajipokok->fm_gaji }} </td></tr>
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection