routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::group(['middleware' => 'auth'], function () {
	Route::get('/', 'HomeController@index')->name('home');
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);

	Route::resource('jabatan', 'JabatanController');
	Route::resource('golongan', 'GolonganController');
	Route::resource('eselon', 'EselonController');
	Route::resource('jabatan-struktural', 'JabatanStrukturalController');
	Route::resource('jabatan-fungsional', 'JabatanFungsionalController');
	Route::resource('gaji-pokok', 'GajiPokokController');

	Route::resource('jusuran-pendidikan', 'JusuranPendidikanController');
	Route::resource('strata-pendidikan', 'StrataPendidikanController');
	Route::resource('diklat-profesi', 'DiklatProfesiController');
	Route::resource('diklat-fungsional', 'DiklatFungsionalController');
	Route::resource('diklat-fungsional', 'DiklatFungsionalController');
	Route::resource('diklat-struktural', 'DiklatStrukturalController');
	Route::resource('pegawai', 'PegawaiController');


	Route::get('kota/{provinsiID}', 'WilayahController@getKota');
	Route::get('kecamatan/{kotaID}', 'WilayahController@getKecamatan');




});

app/JabatanStruktural.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class JabatanStruktural extends Model
{
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'tm_jabstruk';

    protected $primaryKey = null;
    public $incrementing = false;
    public $timestamps = false;
    


    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['fc_kdjabstruk', 'fv_nmjabstruk', 'fc_singkatan', 'fv_jabatan'];

    
}

app/Http/Controllers/JabatanStrukturalController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Http\Requests;

use App\JabatanStruktural;
use Illuminate\Http\Request;

class JabatanStrukturalController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\View\View
     */
    public function index(Request $request)
    {
        $keyword = $request->get('search');
        $perPage = 25;

        if (!empty($keyword)) {
            $jabatanstruktural = JabatanStruktural::where('fc_kdjabstruk', 'LIKE', "%$keyword%")
                ->orWhere('fv_nmjabstruk', 'LIKE', "%$keyword%")
                ->orWhere('fc_singkatan', 'LIKE', "%$keyword%")
                ->orWhere('fv_jabatan', 'LIKE', "%$keyword%")
                ->paginate($perPage);
        } else {
            $jabatanstruktural = JabatanStruktural::paginate($perPage);
        }

        return view('jabatan-struktural.index', compact('jabatanstruktural'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        return view('jabatan-struktural.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'fc_kdjabstruk' => 'required:max:5',
            'fv_nmjabstruk' => 'required|max:20',
            'fc_singkatan' => 'max:50',
            'fv_jabatan' => 'max:50',
        ]);
        
        $requestData = $request->except(['_token','_method']);


        JabatanStruktural::create($requestData);

        return redirect('jabatan-struktural')->with('flash_message', 'JabatanStruktural added!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     *
     * @return \Illuminate\View\View
     */
    public function show($id)
    {
        $jabatanstruktural = JabatanStruktural::findOrFail($id);

        return view('jabatan-struktural.show', compact('jabatanstruktural'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     *
     * @return \Illuminate\View\View
     */
    public function edit($id)
    {
        $jabatanstruktural = JabatanStruktural::where('fc_kdjabstruk',$id)->first();

        return view('jabatan-struktural.edit', compact('jabatanstruktural'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param  int  $id
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'fc_kdjabstruk' => 'required:max:5',
            'fv_nmjabstruk' => 'required|max:20',
            'fc_singkatan' => 'max:50',
            'fv_jabatan' => 'max:50',
        ]);
        
        $requestData = $request->except(['_token','_method']);

        $jabatanstruktural = JabatanStruktural::where('fc_kdjabstruk',$id);

        $jabatanstruktural->update($requestData);

        return redirect('jabatan-struktural')->with('flash_message', 'JabatanStruktural updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy($id)
    {
        JabatanStruktural::where('fc_kdjabstruk',$id)->delete();

        return redirect('jabatan-struktural')->with('flash_message', 'JabatanStruktural deleted!');
    }
}

resources/views/jabatan-struktural/create.blade.php
@extends('layouts.app', ['activePage' => 'jabatan-struktural', 'titlePage' => __('Jabatan struktural')])


@section('content')
<div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Create New Jabatan Struktural</div>
                <div class="card-body">
                    <a href="{{ url('/jabatan-struktural') }}" title="Back"><button class="btn btn-warning btn-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> Back</button></a>
                    <br />
                    <br />

                    @if ($errors->any())
                    <div class="alert alert-danger"  role="alert">
                        <ul >
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                    <br>
                    @endif

                    <form method="POST" action="{{ url('/jabatan-struktural') }}" accept-charset="UTF-8" class="form-horizontal" enctype="multipart/form-data">
                        {{ csrf_field() }}

                        @include ('jabatan-struktural.form', ['formMode' => 'create'])

                    </form>

                </div>

            </div>
        </div>
    </div>
    </div>
</div>
@endsection

resources/views/jabatan-struktural/edit.blade.php
@extends('layouts.app', ['activePage' => 'jabatan-struktural', 'titlePage' => __('Jabatan struktural')])


@section('content')
<div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
            <div class="card">
                    <div class="card-header">Edit JabatanStruktural #{{ $jabatanstruktural->fc_kdjabstruk }}</div>
                    <div class="card-body">
                        <a href="{{ url('/jabatan-struktural') }}" title="Back"><button class="btn btn-warning btn-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> Back</button></a>
                        <br />
                        <br />

                       @if ($errors->any())
                        <div class="alert alert-danger"  role="alert">
                            <ul >
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                        <br>
                        @endif

                        <form action="{{ route('jabatan-struktural.update',$jabatanstruktural->fc_kdjabstruk) }}" method="POST">
                            @csrf
                            @method('PUT')

                            @include ('jabatan-struktural.form', ['formMode' => 'edit'])

                        </form>

                    </div>
                </div>
        </div>
    </div>
    </div>
</div>
@endsection

resources/views/jabatan-struktural/form.blade.php
<div class="form-group {{ $errors->has('fc_kdjabstruk') ? 'has-error' : ''}}">
    <label for="fc_kdjabstruk" class="control-label">{{ 'Fc Kdjabstruk' }}</label>
    <input class="form-control" name="fc_kdjabstruk" type="text" id="fc_kdjabstruk" value="{{ isset($jabatanstruktural->fc_kdjabstruk) ? $jabatanstruktural->fc_kdjabstruk : ''}}" >
    {!! $errors->first('fc_kdjabstruk', '<p class="help-block">:message</p>') !!}
</div>
<div class="form-group {{ $errors->has('fv_nmjabstruk') ? 'has-error' : ''}}">
    <label for="fv_nmjabstruk" class="control-label">{{ 'Fv Nmjabstruk' }}</label>
    <input class="form-control" name="fv_nmjabstruk" type="text" id="fv_nmjabstruk" value="{{ isset($jabatanstruktural->fv_nmjabstruk) ? $jabatanstruktural->fv_nmjabstruk : ''}}" >
    {!! $errors->first('fv_nmjabstruk', '<p class="help-block">:message</p>') !!}
</div>
<div class="form-group {{ $errors->has('fc_singkatan') ? 'has-error' : ''}}">
    <label for="fc_singkatan" class="control-label">{{ 'Fc Singkatan' }}</label>
    <input class="form-control" name="fc_singkatan" type="text" id="fc_singkatan" value="{{ isset($jabatanstruktural->fc_singkatan) ? $jabatanstruktural->fc_singkatan : ''}}" >
    {!! $errors->first('fc_singkatan', '<p class="help-block">:message</p>') !!}
</div>
<div class="form-group {{ $errors->has('fv_jabatan') ? 'has-error' : ''}}">
    <label for="fv_jabatan" class="control-label">{{ 'Fv Jabatan' }}</label>
    <input class="form-control" name="fv_jabatan" type="text" id="fv_jabatan" value="{{ isset($jabatanstruktural->fv_jabatan) ? $jabatanstruktural->fv_jabatan : ''}}" >
    {!! $errors->first('fv_jabatan', '<p class="help-block">:message</p>') !!}
</div>


<div class="form-group">
    <input class="btn btn-primary" type="submit" value="{{ $formMode === 'edit' ? 'Update' : 'Create' }}">
</div>

resources/views/jabatan-struktural/index.blade.php
@extends('layouts.app', ['activePage' => 'jabatan-struktural', 'titlePage' => __('Jabatan Struktural')])

@section('content')
  <div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                        <div class="card-header">Jabatan Struktural</div>
                        <div class="card-body">
                            <a href="{{ url('/jabatan-struktural/create') }}" class="btn btn-success btn-sm" title="Add New JabatanStruktural">
                                <i class="fa fa-plus" aria-hidden="true"></i> Add New
                            </a>

                            <form method="GET" action="{{ url('/jabatan-struktural') }}" accept-charset="UTF-8" class="form-inline my-2 my-lg-0 float-right" role="search">
                                <div class="input-group">
                                    <input type="text" class="form-control" name="search" placeholder="Search..." value="{{ request('search') }}">
                                    <span class="input-group-append">
                                        <button class="btn btn-secondary" type="submit">
                                            <i class="fa fa-search"></i>
                                        </button>
                                    </span>
                                </div>
                            </form>

                            <br/>
                            <br/>
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>Fc Kdjabstruk</th><th>Fv Nmjabstruk</th><th>Fc Singkatan</th><th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($jabatanstruktural as $item)
                                        <tr>
                                            <td>{{ $item->fc_kdjabstruk }}</td><td>{{ $item->fv_nmjabstruk }}</td><td>{{ $item->fc_singkatan }}</td>
                                            <td>

                                                <a href="{{ url('/jabatan-struktural/' . $item->fc_kdjabstruk . '/edit') }}" title="Edit JabatanStruktural"><button class="btn btn-primary btn-sm"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit</button></a>

                                                <form method="POST" action="{{ url('/jabatan-struktural' . '/' . $item->fc_kdjabstruk) }}" accept-charset="UTF-8" style="display:inline">
                                                    {{ method_field('DELETE') }}
                                                    {{ csrf_field() }}
                                                    <button type="submit" class="btn btn-danger btn-sm" title="Delete JabatanStruktural" onclick="return confirm(&quot;Confirm delete?&quot;)"><i class="fa fa-trash-o" aria-hidden="true"></i> Delete</button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                                <div class="pagination-wrapper"> {!! $jabatanstruktural->appends(['search' => Request::get('search')])->render() !!} </div>
                            </div>

                        </div>
                    </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/jabatan-struktural/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            @include('admin.sidebar')

            <div class="col-md-9">
                <div class="card">
                    <div class="card-header">JabatanStruktural {{ $jabatanstruktural->id }}</div>
                    <div class="card-body">

                        <a href="{{ url('/jabatan-struktural') }}" title="Back"><button class="btn btn-warning btn-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> Back</button></a>
                        <a href="{{ url('/jabatan-struktural/' . $jabatanstruktural->id . '/edit') }}" title="Edit JabatanStruktural"><button class="btn btn-primary btn-sm"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit</button></a>

                        <form method="POST" action="{{ url('jabatanstruktural' . '/' . $jabatanstruktural->id) }}" accept-charset="UTF-8" style="display:inline">
                            {{ method_field('DELETE') }}
                            {{ csrf_field() }}
                            <button type="submit" class="btn btn-danger btn-sm" title="Delete JabatanStruktural" onclick="return confirm(&quot;Confirm delete?&quot;)"><i class="fa fa-trash-o" aria-hidden="true"></i> Delete</button>
                        </form>
                        <br/>
                        <br/>

                        <div class="table-responsive">
                            <table class="table">
                                <tbody>
                                    <tr>
                                        <th>ID</th><td>{{ $jabatanstruktural->id }}</td>
                                    </tr>
                                    <tr><th> Fc Kdjabstruk </th><td> {{ $jabatanstruktural->fc_kdjabstruk }} </td></tr><tr><th> Fv Nmjabstruk </th><td> {{ $jabatanstruktural->fv_nmjabstruk }} </td></tr><tr><th> Fc Singkatan </th><td> {{ $jabatanstruktural->fc_singkatan }} </td></tr>
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection